default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root
  password: 12345678
  host: localhost

development:
  <<: *default
  database: bulk_mail_mvp_development

production:
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["MYSQLHOST"] %>
  port: <%= ENV["MYSQLPORT"] %>
  database: <%= ENV["MYSQLDATABASE"] %>
  username: <%= ENV["MYSQLUSER"] %>
  password: <%= ENV["MYSQLPASSWORD"] %>
